name: env_intaros
channels:
  - terradue
  - conda-forge
dependencies:
  - python=3.7
  - pydap
  - ipykernel
  - shapely
  - requests
  - pip
  - lxml
  - pyyaml
  - matplotlib
  - xarray
  - geopandas
  - bokeh
  - rpy2
  - r-rcpp
  - r-maps
  - r-mapdata
  - r-mapproj
  - r-ncdf4
  - r-png 
  - r-fields
  - r-maptools
  - r-proj4
  - r-raster
  - r-rgdal
  - r-gsl
  - r-misc3d